workflows:
  android-app:
    name: Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.example.scamcalldetector"
      java: 11
    
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Install Gradle
        script: |
          cd $CM_BUILD_DIR
          # Install Gradle
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip
          export GRADLE_HOME=$CM_BUILD_DIR/gradle-7.6
          export PATH=$GRADLE_HOME/bin:$PATH
          
          # Create Gradle wrapper files
          gradle wrapper
          
          # Verify Gradle and wrapper installation
          gradle --version
          ./gradlew --version

      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Build Android app
        script: |
          cd $CM_BUILD_DIR
          # Clean and build
          ./gradlew clean assembleDebug --stacktrace
          
      - name: Run tests
        script: |
          cd $CM_BUILD_DIR
          ./gradlew test --stacktrace
          
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/reports/tests/test/*
    publishing:
      email:
        recipients:
          - paulf.hague@gmail.com
        notify:
          success: true
          failure: true 
