workflows:
  android-app:
    name: Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.example.scamcalldetector"
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Clean build directory
        script: |
          ./gradlew clean
      - name: Build Android app
        script: |
          ./gradlew assembleDebug
    artifacts:
      - build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - paulf.hague@gmail.com
        notify:
          success: true
          failure: true 