workflows:
  android-app:
    name: Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.example.scamcalldetector"
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
      - name: Set up Gradle
        script: |
          cd $FCI_BUILD_DIR
          gradle wrapper
      - name: Clean build directory
        script: |
          cd $FCI_BUILD_DIR
          chmod +x ./gradlew
          ./gradlew clean
      - name: Build Android app
        script: |
          cd $FCI_BUILD_DIR
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - paulf.hague@gmail.com
        notify:
          success: true
          failure: true 