workflows:
  android-app:
    name: Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.example.scamcalldetector"
        GRADLE_OPTS: "-Dorg.gradle.logging.level=debug -Dorg.gradle.console=plain -Dorg.gradle.warning.mode=all"
      java: 11
  
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set up project structure
        script: |
          cd $CM_BUILD_DIR
          # Create necessary directories
          mkdir -p app/src/main/java/com/example/scamcalldetector
          mkdir -p app/src/main/res/layout
          mkdir -p app/src/main/res/values
          mkdir -p app/src/main/res/drawable

      - name: Create Gradle wrapper
        script: |
          cd $CM_BUILD_DIR
          # Create wrapper files
          mkdir -p gradle/wrapper
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          
          # Download wrapper jar
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/v7.6.0/gradle/wrapper/gradle-wrapper.jar
          
          # Create gradlew script
          echo '#!/usr/bin/env sh' > gradlew
          curl -L https://raw.githubusercontent.com/gradle/gradle/v7.6.0/gradlew >> gradlew
          chmod +x gradlew
          
          # Create gradlew.bat
          curl -L -o gradlew.bat https://raw.githubusercontent.com/gradle/gradle/v7.6.0/gradlew.bat

      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Create basic Android resources
        script: |
          cd $CM_BUILD_DIR
          # Create basic layout file
          mkdir -p app/src/main/res/layout
          echo '<?xml version="1.0" encoding="utf-8"?>' > app/src/main/res/layout/activity_main.xml
          echo '<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"' >> app/src/main/res/layout/activity_main.xml
          echo '    android:layout_width="match_parent"' >> app/src/main/res/layout/activity_main.xml
          echo '    android:layout_height="match_parent">' >> app/src/main/res/layout/activity_main.xml
          echo '</androidx.constraintlayout.widget.ConstraintLayout>' >> app/src/main/res/layout/activity_main.xml
          
          # Create strings.xml
          mkdir -p app/src/main/res/values
          echo '<?xml version="1.0" encoding="utf-8"?>' > app/src/main/res/values/strings.xml
          echo '<resources>' >> app/src/main/res/values/strings.xml
          echo '    <string name="app_name">Scam Call Detector</string>' >> app/src/main/res/values/strings.xml
          echo '</resources>' >> app/src/main/res/values/strings.xml
          
          # Create AndroidManifest.xml
          mkdir -p app/src/main
          echo '<?xml version="1.0" encoding="utf-8"?>' > app/src/main/AndroidManifest.xml
          echo '<manifest xmlns:android="http://schemas.android.com/apk/res/android">' >> app/src/main/AndroidManifest.xml
          echo '    <application' >> app/src/main/AndroidManifest.xml
          echo '        android:allowBackup="true"' >> app/src/main/AndroidManifest.xml
          echo '        android:icon="@mipmap/ic_launcher"' >> app/src/main/AndroidManifest.xml
          echo '        android:label="@string/app_name"' >> app/src/main/AndroidManifest.xml
          echo '        android:supportsRtl="true"' >> app/src/main/AndroidManifest.xml
          echo '        android:theme="@style/Theme.AppCompat.Light.DarkActionBar">' >> app/src/main/AndroidManifest.xml
          echo '        <activity android:name=".MainActivity" android:exported="true">' >> app/src/main/AndroidManifest.xml
          echo '            <intent-filter>' >> app/src/main/AndroidManifest.xml
          echo '                <action android:name="android.intent.action.MAIN" />' >> app/src/main/AndroidManifest.xml
          echo '                <category android:name="android.intent.category.LAUNCHER" />' >> app/src/main/AndroidManifest.xml
          echo '            </intent-filter>' >> app/src/main/AndroidManifest.xml
          echo '        </activity>' >> app/src/main/AndroidManifest.xml
          echo '    </application>' >> app/src/main/AndroidManifest.xml
          echo '</manifest>' >> app/src/main/AndroidManifest.xml
          
          # Create MainActivity.kt
          mkdir -p app/src/main/java/com/example/scamcalldetector
          echo 'package com.example.scamcalldetector' > app/src/main/java/com/example/scamcalldetector/MainActivity.kt
          echo '' >> app/src/main/java/com/example/scamcalldetector/MainActivity.kt
          echo 'import androidx.appcompat.app.AppCompatActivity' >> app/src/main/java/com/example/scamcalldetector/MainActivity.kt
          echo 'import android.os.Bundle' >> app/src/main/java/com/example/scamcalldetector/MainActivity.kt
          echo '' >> app/src/main/java/com/example/scamcalldetector/MainActivity.kt
          echo 'class MainActivity : AppCompatActivity() {' >> app/src/main/java/com/example/scamcalldetector/MainActivity.kt
          echo '    override fun onCreate(savedInstanceState: Bundle?) {' >> app/src/main/java/com/example/scamcalldetector/MainActivity.kt
          echo '        super.onCreate(savedInstanceState)' >> app/src/main/java/com/example/scamcalldetector/MainActivity.kt
          echo '        setContentView(R.layout.activity_main)' >> app/src/main/java/com/example/scamcalldetector/MainActivity.kt
          echo '    }' >> app/src/main/java/com/example/scamcalldetector/MainActivity.kt
          echo '}' >> app/src/main/java/com/example/scamcalldetector/MainActivity.kt

      - name: Verify Gradle setup
        script: |
          cd $CM_BUILD_DIR
          ./gradlew --version
          ls -la
          ls -la app/
          ls -la gradle/wrapper/

      - name: Build Android app
        script: |
          cd $CM_BUILD_DIR
          # Show full error output
          ./gradlew clean assembleDebug --console=plain --stacktrace --info
          
      - name: Run tests
        script: |
          cd $CM_BUILD_DIR
          ./gradlew test --console=plain --stacktrace --info
          
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/reports/tests/test/*
      - app/build/reports/**/*.html
    publishing:
      email:
        recipients:
          - paulf.hague@gmail.com
        notify:
          success: true
          failure: true 
