workflows:
  android-app:
    name: Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.example.scamcalldetector"
      java: 11
    
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set up project structure
        script: |
          cd $CM_BUILD_DIR
          # Create necessary directories
          mkdir -p app/src/main/java/com/example/scamcalldetector
          mkdir -p app/src/main/res/layout
          mkdir -p app/src/main/res/values

      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Set up Gradle
        script: |
          cd $CM_BUILD_DIR
          # Download and install Gradle
          wget -q https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip -q gradle-7.6-bin.zip
          export GRADLE_HOME=$CM_BUILD_DIR/gradle-7.6
          export PATH=$GRADLE_HOME/bin:$PATH
          
          # Verify Gradle installation
          gradle -v
          
          # Generate Gradle wrapper files
          gradle wrapper
          
          # Make wrapper executable
          chmod +x gradlew
          
          # Verify wrapper
          ./gradlew -v
      
      - name: Build Android app
        script: |
          cd $CM_BUILD_DIR
          # Clean and build debug APK (no signing)
          ./gradlew clean assembleDebug --stacktrace
          
      - name: Run tests
        script: |
          cd $CM_BUILD_DIR
          ./gradlew test --stacktrace
          
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/reports/tests/test/*
    publishing:
      email:
        recipients:
          - paulf.hague@gmail.com
        notify:
          success: true
          failure: true 
