workflows:
  android-app:
    name: Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.example.scamcalldetector"
      java: 11
      android_sdk: 33
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set up project structure
        script: |
          cd $CM_BUILD_DIR
          # Create necessary directories
          mkdir -p app/src/main/java/com/example/scamcalldetector
          mkdir -p app/src/main/res/layout
          mkdir -p app/src/main/res/values

      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Create Gradle wrapper
        script: |
          cd $CM_BUILD_DIR
          # Create wrapper files
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          
          # Download wrapper jar
          mkdir -p gradle/wrapper
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/v7.6.0/gradle/wrapper/gradle-wrapper.jar
          
          # Create gradlew script
          echo '#!/usr/bin/env sh' > gradlew
          curl -L https://raw.githubusercontent.com/gradle/gradle/v7.6.0/gradlew >> gradlew
          chmod +x gradlew
          
          # Create gradlew.bat
          curl -L -o gradlew.bat https://raw.githubusercontent.com/gradle/gradle/v7.6.0/gradlew.bat
          
          # Verify wrapper
          ./gradlew --version
      
      - name: Build Android app
        script: |
          cd $CM_BUILD_DIR
          # Clean and build debug APK (no signing)
          ./gradlew clean assembleDebug --stacktrace
          
      - name: Run tests
        script: |
          cd $CM_BUILD_DIR
          ./gradlew test --stacktrace
          
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/reports/tests/test/*
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true 